# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer2.weshare.com:
  orderer3.weshare.com:
  orderer4.weshare.com:
  orderer5.weshare.com:

networks:
  byfn:

services:

  orderer2.weshare.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer2.weshare.com
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/weshare.com/orderers/orderer2.weshare.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/weshare.com/orderers/orderer2.weshare.com/tls/:/var/hyperledger/orderer/tls
        - orderer2.weshare.com:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3.weshare.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer3.weshare.com
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/weshare.com/orderers/orderer3.weshare.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/weshare.com/orderers/orderer3.weshare.com/tls/:/var/hyperledger/orderer/tls
        - orderer3.weshare.com:/var/hyperledger/production/orderer
    ports:
    - 9050:7050

  orderer4.weshare.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer4.weshare.com
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/weshare.com/orderers/orderer4.weshare.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/weshare.com/orderers/orderer4.weshare.com/tls/:/var/hyperledger/orderer/tls
        - orderer4.weshare.com:/var/hyperledger/production/orderer
    ports:
    - 10050:7050

  orderer5.weshare.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer5.weshare.com
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/weshare.com/orderers/orderer5.weshare.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/weshare.com/orderers/orderer5.weshare.com/tls/:/var/hyperledger/orderer/tls
        - orderer5.weshare.com:/var/hyperledger/production/orderer
    ports:
    - 11050:7050
